PojisteniApp2/Models/Insurance.cs
using PojisteniApp2.Helpers;
using System.ComponentModel.DataAnnotations;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace PojisteniApp2.Models
{
    public class Insurance : IAuthor
    {
        [Display(Name = "ID Pojištění")]
        public int InsuranceId { get; set; }

        [Display(Name = "ID Typu pojištění")]
        public int InsuranceTypeId { get; set; }

        [Display(Name = "Typ pojištění")]
        public InsuranceType? InsuranceType { get; set; }

        [Display(Name = "Částka")]
        [Range(1000, 1000000000, ErrorMessage = "{0} musí být mezi {1} a {2}")]
        [DisplayFormat(DataFormatString = "{0:# ### ### ### Kč}")]
        public int InsuranceAmount { get; set; }

        [Display(Name = "Předmět pojištění")]
        [Required(ErrorMessage = "Vyplňte předmět pojištění")]
        [StringLength(150, ErrorMessage = "Maximální délka předmětu pojištění je 150 znaků")]
        public string InsuranceSubject { get; set; } = string.Empty;

        [Display(Name = "Platnost od")]
        [Required(ErrorMessage = "Vyplňte platnost od")]
        [DateRange(nameof(ValidFrom), nameof(ValidTo))]
        [DataType(DataType.Date)]
        public DateTime ValidFrom { get; set; } = DateTime.MinValue;

        [Display(Name = "Platnost do")]
        [Required(ErrorMessage = "Vyplňte platnost do")]
        [DateRange(nameof(ValidFrom), nameof(ValidTo))]
        [DataType(DataType.Date)]
        public DateTime ValidTo { get; set; } = DateTime.MaxValue;

        [Display(Name = "ID Pojištěnce")]
        public int PersonId { get; set; }

        [Display(Name = "Pojištěnec")]
        public Person? Person { get; set; }

        [StringLength(450)]
        public string? AuthorId { get; set; }
    }
}

PojisteniApp2/Models/InsuranceType.cs
using System.ComponentModel.DataAnnotations;

namespace PojisteniApp2.Models
{
    public class InsuranceType
    {
        public int InsuranceTypeId { get; set; }

        [Required]
        [StringLength(50)]
        public string InsuranceTypeName { get; set; } = string.Empty;
    }
}

PojisteniApp2/Controllers/InsurancesController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PojisteniApp2.Data;
using PojisteniApp2.Helpers;
using PojisteniApp2.Models;

namespace PojisteniApp2.Controllers
{
    public class InsurancesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly INotyfService _notyf;
        private readonly string _genericErrorMessage = "Opravte zadaná data";

        public InsurancesController(ApplicationDbContext context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }

        // GET: Insurances
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            // Can be assigned whatever string you want, but the keyword needs to be consistent throughout this method
            string personCustomSortKeyword = "Person";

            // Sort based on tutorial: https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/advanced?view=aspnetcore-7.0#dynamic-linq
            ViewData["CurrentSort"] = sortOrder;
            ViewData["PersonSortParm"] = string.IsNullOrEmpty(sortOrder) ? $"{personCustomSortKeyword}_desc" : "";
            ViewData["AmountSortParm"] = sortOrder == "InsuranceAmount" ? "InsuranceAmount_desc" : "InsuranceAmount";
            ViewData["ValidFromSortParm"] = sortOrder == "ValidFrom" ? "ValidFrom_desc" : "ValidFrom";
            ViewData["ValidToSortParm"] = sortOrder == "ValidTo" ? "ValidTo_desc" : "ValidTo";
            // Paging based on tutorial: https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-7.0#add-paging-to-students-index
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            // Search based on tutorial: https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-7.0#add-filtering-functionality-to-the-index-method
            ViewData["CurrentFilter"] = searchString;

            var insurances = (IQueryable<Insurance>)_context.Insurance.Include(i => i.InsuranceType).Include(i => i.Person);

            if (!String.IsNullOrEmpty(searchString))
            {
                insurances = insurances.Where(e => e.Person.LastName.Contains(searchString) || e.Person.FirstName.Contains(searchString));
            }

            if (string.IsNullOrEmpty(sortOrder))
            {
                sortOrder = personCustomSortKeyword;
            }

            bool descending = false;
            if (sortOrder.EndsWith("_desc"))
            {
                // Trim _desc suffix
                sortOrder = sortOrder.Substring(0, sortOrder.Length - 5);
                descending = true;
            }

            if (descending)
            {
                // Custom sort by Person properties
                if (sortOrder == personCustomSortKeyword)
                {
                    insurances = insurances.OrderByDescending(e => e.Person.LastName)
                                            .ThenByDescending(e => e.Person.FirstName)
                                            .ThenByDescending(e => e.Person.City)
                                            .ThenByDescending(e => e.Person.Street);
                }
                // Generic sort by all other Insurance properties
                else
                {
                    insurances = insurances.OrderByDescending(e => EF.Property<object>(e, sortOrder));
                }
            }
            else
            {
                if (sortOrder == personCustomSortKeyword)
                {
                    insurances = insurances.OrderBy(e => e.Person.LastName)
                                            .ThenBy(e => e.Person.FirstName)
                                            .ThenBy(e => e.Person.City)
                                            .ThenBy(e => e.Person.Street);
                }
                else
                {
                    insurances = insurances.OrderBy(e => EF.Property<object>(e, sortOrder));
                }
            }

            int pageSize = 3;
            return View(await PaginatedList<Insurance>.CreateAsync(insurances.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Insurances/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Insurance == null)
            {
                return NotFound();
            }

            var insurance = await _context.Insurance
                .Include(i => i.InsuranceType)
                .Include(i => i.Person)
                .FirstOrDefaultAsync(m => m.InsuranceId == id);
            if (insurance == null)
            {
                return NotFound();
            }

            return View(insurance);
        }

        // GET: Insurances/Create
        public IActionResult Create(int? id)
        {
            ViewData["InsuranceTypeId"] = CreateInsuranceTypeSelectList();
            ViewData["PersonId"] = CreatePersonSelectList(id); // Custom list of persons created by current user or all persons if current user is admin
            ViewData["IsDefinedPerson"] = false;
            ViewData["CustomTitle"] = "Nové pojištění";
            TempData["PreviousUrl"] = Request.Headers["Referer"].ToString(); // Saves URL user is coming from to be used in POST Create action
            // Create insurance instance and assign default values
            Insurance insurance = new Insurance();
            insurance.ValidFrom = DateTime.Now.Date;
            insurance.ValidTo = insurance.ValidFrom.AddYears(1);
            if (id != null) // PersonId was routed to this action
            {
                // Insurance will be created for person defined by PersonId
                ViewData["IsDefinedPerson"] = true;
                insurance.PersonId = (int)id;

                // Person name for the view title
                var person = _context.Person.Find(id);
                if (person != null)
                {
                    ViewData["CustomTitle"] = ViewData["CustomTitle"] + string.Format($" {person.FirstName.Substring(0, 1).ToUpper()}. {person.LastName}");
                }
            }

            // Assign string "disabled" if no user logged in
            ViewBag.Disabled = UserHelper.IsLoggedUser(User) ? string.Empty : "disabled";

            return View(insurance);
        }

        // POST: Insurances/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Authorize]
		public async Task<IActionResult> Create([Bind("InsuranceId,InsuranceTypeId,InsuranceAmount,InsuranceSubject,ValidFrom,ValidTo,PersonId")] Insurance insurance)
        {
            if (ModelState.IsValid)
            {
                // Set currently logged in user's id as AuthorId
                insurance.AuthorId = UserHelper.GetUserId(User);
                _context.Add(insurance);
                await _context.SaveChangesAsync();
                _notyf.Success("Nové pojištění přidáno");

                // Redirect to previous URL if available
                if (TryGetPreviousUrl(out string previousUrl))
                {
                    return Redirect(previousUrl);
                }

                // Redirect to defaul action People -> Details if condition above is not true
                return RedirectToAction("Details", "People", new { id = insurance.PersonId });
            }
            ViewData["InsuranceTypeId"] = CreateInsuranceTypeSelectList(insurance.InsuranceTypeId);
            ViewData["PersonId"] = CreatePersonSelectList(insurance.PersonId); // Custom list of persons created by current user or all persons if current user is admin
            ViewData["IsDefinedPerson"] = false;
            ViewData["CustomTitle"] = "Nové pojištění";
            // Person name for the view title
            var person = _context.Person.Find(insurance.PersonId);
            if (person != null)
            {
                ViewData["IsDefinedPerson"] = true;
                ViewData["CustomTitle"] = ViewData["CustomTitle"] + string.Format($" {person.FirstName.Substring(0, 1).ToUpper()}. {person.LastName}");
            }

            // No disabled functionality for POST method of Create action needed
            ViewBag.Disabled = string.Empty;

            _notyf.Error(_genericErrorMessage);
            return View(insurance);
        }

        // GET: Insurances/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Insurance == null)
            {
                return NotFound();
            }

            var insurance = await _context.Insurance.FindAsync(id);
            if (insurance == null)
            {
                return NotFound();
            }
            ViewData["InsuranceTypeId"] = CreateInsuranceTypeSelectList(insurance.InsuranceTypeId);
            ViewData["PersonId"] = CreatePersonSelectList(insurance.PersonId); // Custom list of persons created by current user or all persons if current user is admin
            TempData["PreviousUrl"] = Request.Headers["Referer"].ToString(); // Saves URL user is coming from to be used in POST Edit action
            // Assign string "disabled" if current user is neither author nor admin

PojisteniApp2/Views/Insurances/Create.cshtml
@model PojisteniApp2.Models.Insurance

@{
    ViewData["Title"] = "Nové pojištění";
}

<form asp-action="Create">
	<div class="row bg-dark bg-opacity-50 py-3 ps-4 pe-2 d-flex">
		<div class="col-auto text-white d-flex align-items-center">
            <h1>@ViewData["CustomTitle"]</h1>
		</div>
		<div class="col d-flex align-items-center justify-content-end">
            <span class="disabled-title-wrapper">
                <button type="submit" class="btn btn-lg btn-primary @ViewBag.Disabled" tabindex="7"><i class="fa-solid fa-check"></i></button>
            </span>
		</div>
	</div>
	<div class="row bg-light pt-2 pb-4 py-lg-4 px-3 px-md-5 mt-1">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-12 col-md-6 col-lg-5 col-xl-4">
            <div class="form-group mt-1">
                <label asp-for="InsuranceType" class="control-label"></label>
                <select asp-for="InsuranceTypeId" class="form-control" asp-items="ViewBag.InsuranceTypeId" tabindex="1"></select>
                <span asp-validation-for="InsuranceTypeId" class="text-danger"></span>
            </div>
            <div class="form-group mt-1">
                <label asp-for="InsuranceAmount" class="control-label"></label>
                <input asp-for="InsuranceAmount" class="form-control" min="1000" max="1000000000" step="1000" tabindex="2" />
                <span asp-validation-for="InsuranceAmount" class="text-danger"></span>
            </div>
            <div class="form-group mt-1">
                <label asp-for="InsuranceSubject" class="control-label"></label>
                <input asp-for="InsuranceSubject" class="form-control" tabindex="3" />
                <span asp-validation-for="InsuranceSubject" class="text-danger"></span>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-5 col-xl-4">
            <div class="form-group mt-1">
                <label asp-for="ValidFrom" class="control-label"></label>
                <input asp-for="ValidFrom" class="form-control" tabindex="4" />
                <span asp-validation-for="ValidFrom" class="text-danger"></span>
            </div>
            <div class="form-group mt-1">
                <label asp-for="ValidTo" class="control-label"></label>
                <input asp-for="ValidTo" class="form-control" tabindex="5" />
                <span asp-validation-for="ValidTo" class="text-danger"></span>
            </div>
            <div @if (ViewBag.IsDefinedPerson)
            {
                <text>style = "display: none"</text>
            }
            class="form-group mt-1">
                <label asp-for="Person" class="control-label"></label>
                <select asp-for="PersonId" class="form-control" asp-items="ViewBag.PersonId" tabindex="6"></select>
                <span asp-validation-for="PersonId" class="text-danger"></span>
            </div>
        </div>
	</div>
</form>

PojisteniApp2/Views/Insurances/Delete.cshtml
@model PojisteniApp2.Models.Insurance

@{
    ViewData["Title"] = "Odstranění pojištění";
}

<div class="row bg-dark bg-opacity-50 py-3 ps-4 pe-2 d-flex">
    <div class="col-auto text-white d-flex align-items-center">
        <h1>Smazat pojištnění?</h1>
    </div>
    <div class="col d-flex align-items-center justify-content-end"> 
        <form asp-action="Delete">
            <input type="hidden" asp-for="InsuranceId" />
            <span class="disabled-title-wrapper">
                <button type="submit" class="btn btn-lg btn-danger @ViewBag.Disabled" tabindex="1"><i class="fa-solid fa-trash-can"></i></button>
            </span>
        </form>
    </div>
</div>
<div class="row dl-local-style bg-light py-2 py-md-4 px-3 px-md-5 mt-1 text-center text-sm-start">
    <dl class="col-12 col-sm-6 col-lg-5 col-xl-4 d-flex flex-column justify-content-evenly m-0">
        @* <div> to keep elements always together *@
        <div>
            <dt>
                @Html.DisplayNameFor(model => model.InsuranceType)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.InsuranceType.InsuranceTypeName)
            </dd>
        </div>
        <div>
            <dt>
                @Html.DisplayNameFor(model => model.InsuranceAmount)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.InsuranceAmount)
            </dd>
        </div>
        <div>
            <dt>
                @Html.DisplayNameFor(model => model.InsuranceSubject)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.InsuranceSubject)
            </dd>
        </div>
    </dl>
    <dl class="col-12 col-sm-6 col-lg-5 col-xl-4 d-flex flex-column justify-content-evenly m-0">
        <div>
            <dt>
                @Html.DisplayNameFor(model => model.ValidFrom)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ValidFrom)
            </dd>
        </div>
        <div>
            <dt>
                @Html.DisplayNameFor(model => model.ValidTo)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ValidTo)
            </dd>
        </div>
        <div>
            <dt>
                @Html.DisplayNameFor(model => model.Person)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Person.FullNameWithAddress)
            </dd>
        </div>
    </dl>
</div>

PojisteniApp2/Views/Insurances/Details.cshtml
@model PojisteniApp2.Models.Insurance

@{
    ViewData["Title"] = "Detail pojištění";
}

<div class="row bg-dark bg-opacity-50 py-3 ps-4 pe-2 d-flex">
    <div class="col-auto text-white d-flex align-items-center">
        <h1>@ViewData["Title"]</h1>
    </div>
    <div class="col d-flex align-items-center justify-content-end">
        <a asp-action="Edit" class="btn btn-lg btn-secondary" asp-route-id="@Model?.InsuranceId" tabindex="1"><i class="fa-solid fa-pen-to-square"></i></a>
        <a asp-controller="People" asp-action="Details" class="btn btn-lg btn-secondary ms-1" asp-route-id="@Model?.PersonId" tabindex="2"><i class="fa-solid fa-user"></i></a>
    </div>
</div>
<div class="row dl-local-style bg-light py-2 py-md-4 px-3 px-md-5 mt-1 text-center text-sm-start">
    <dl class="col-12 col-sm-6 col-lg-5 col-xl-4 d-flex flex-column justify-content-evenly m-0">
        @* <div> to keep elements always together *@
        <div>
            <dt>
                @Html.DisplayNameFor(model => model.InsuranceType)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.InsuranceType.InsuranceTypeName)
            </dd>
        </div>
        <div>
            <dt>
                @Html.DisplayNameFor(model => model.InsuranceAmount)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.InsuranceAmount)
            </dd>
        </div>
        <div>
            <dt>
                @Html.DisplayNameFor(model => model.InsuranceSubject)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.InsuranceSubject)
            </dd>
        </div>
    </dl>
    <dl class="col-12 col-sm-6 col-lg-5 col-xl-4 d-flex flex-column justify-content-evenly m-0">
        <div>
            <dt>
                @Html.DisplayNameFor(model => model.ValidFrom)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ValidFrom)
            </dd>
        </div>
        <div>
            <dt>
                @Html.DisplayNameFor(model => model.ValidTo)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ValidTo)
            </dd>
        </div>
        <div>
            <dt>
                @Html.DisplayNameFor(model => model.Person)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Person.FullNameWithAddress)
            </dd>
        </div>
    </dl>
</div>

PojisteniApp2/Views/Insurances/Edit.cshtml
@model PojisteniApp2.Models.Insurance

@{
    ViewData["Title"] = "Editace pojištění";
}

<form asp-action="Edit">
    <div class="row bg-dark bg-opacity-50 py-3 ps-4 pe-2 d-flex">
        <div class="col-auto text-white d-flex align-items-center">
            <h1>@ViewData["Title"]</h1>
        </div>
        <div class="col d-flex align-items-center justify-content-end">
            <span class="disabled-title-wrapper">
                <button type="submit" class="btn btn-lg btn-primary @ViewBag.Disabled" tabindex="7"><i class="fa-solid fa-check"></i></button>
            </span>
        </div>
    </div>
    <div class="row bg-light pt-2 pb-4 py-lg-4 px-3 px-md-5 mt-1">
        <input type="hidden" asp-for="InsuranceId" />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-12 col-md-6 col-lg-5 col-xl-4">
            <div class="form-group mt-1">
                <label asp-for="InsuranceType" class="control-label"></label>
                <select asp-for="InsuranceTypeId" class="form-control" asp-items="ViewBag.InsuranceTypeId" tabindex="1"></select>
                <span asp-validation-for="InsuranceTypeId" class="text-danger"></span>
            </div>
            <div class="form-group mt-1">
                <label asp-for="InsuranceAmount" class="control-label"></label>
                <input asp-for="InsuranceAmount" class="form-control" min="1000" max="1000000000" step="1000" tabindex="2" />
                <span asp-validation-for="InsuranceAmount" class="text-danger"></span>
            </div>
            <div class="form-group mt-1">
                <label asp-for="InsuranceSubject" class="control-label"></label>
                <input asp-for="InsuranceSubject" class="form-control" tabindex="3" />
                <span asp-validation-for="InsuranceSubject" class="text-danger"></span>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-5 col-xl-4">
            <div class="form-group mt-1">
                <label asp-for="ValidFrom" class="control-label"></label>
                <input asp-for="ValidFrom" class="form-control" tabindex="4" />
                <span asp-validation-for="ValidFrom" class="text-danger"></span>
            </div>
            <div class="form-group mt-1">
                <label asp-for="ValidTo" class="control-label"></label>
                <input asp-for="ValidTo" class="form-control" tabindex="5" />
                <span asp-validation-for="ValidTo" class="text-danger"></span>
            </div>
            <div class="form-group mt-1">
                <label asp-for="Person" class="control-label"></label>
                <select asp-for="PersonId" class="form-control" asp-items="ViewBag.PersonId" tabindex="6"></select>
                <span asp-validation-for="PersonId" class="text-danger"></span>
            </div>
        </div>
    </div>
</form>

PojisteniApp2/Views/Insurances/Index.cshtml
@using PojisteniApp2.Helpers;

@model PaginatedList<PojisteniApp2.Models.Insurance>

@{
    ViewData["Title"] = "Pojištění";
}
<div class="row bg-dark bg-opacity-50 py-3 ps-4 pe-2 d-flex">
    <div class="col-auto text-white d-flex align-items-center">
        <h1>@ViewData["Title"]</h1>
    </div>
    <div class="col d-flex align-items-center justify-content-end">
        <a asp-action="Create" class="btn btn-lg btn-primary" tabindex="1"><i class="fa-solid fa-plus"></i></a>
    </div>
</div>
<div class="row bg-light py-2 py-md-4 px-3 px-md-5 mt-1">
	<div class="col-12">
		<partial name="_SearchPartial" />
	</div>
    <div class="col-12">
        <table class="table table-hover mt-3">
            <thead>
                <tr>
                    <th>
                        ID Pojištění
                    </th>
                    <th>
                        <a asp-action="Index" asp-route-sortOrder="@ViewData["PersonSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]" class="text-black">Pojištěnec</a>
                    </th>
                    <th>
                        Typ pojištění
                    </th>
                    <th class="d-none d-md-table-cell">
                        <a asp-action="Index" asp-route-sortOrder="@ViewData["AmountSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]" class="text-black">Částka</a>
                    </th>
                    <th class="d-none d-md-table-cell">
                        <a asp-action="Index" asp-route-sortOrder="@ViewData["ValidFromSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]" class="text-black">Platnost od</a>
                    </th>
                    <th>
                        <a asp-action="Index" asp-route-sortOrder="@ViewData["ValidToSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]" class="text-black">Platnost do</a>
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr onclick="window.location.href = '@Url.Action("Details", "Insurances", new { id = item.InsuranceId })'">
                        <td>
                            @Html.DisplayFor(modelItem => item.InsuranceId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Person.FullNameWithAddress)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.InsuranceType.InsuranceTypeName)
                        </td>
                        <td class="d-none d-md-table-cell">
                            @Html.DisplayFor(modelItem => item.InsuranceAmount)
                        </td>
                        <td class="d-none d-md-table-cell">
                            @Html.DisplayFor(modelItem => item.ValidFrom)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ValidTo)
                        </td>
                        <td class="text-end">
                            <a asp-action="Edit" class="btn btn-outline-secondary mb-1" asp-route-id="@item.InsuranceId"><i class="fa-solid fa-pen-to-square"></i></a>
                            <a asp-action="Delete" class="btn btn-outline-secondary mb-1" asp-route-id="@item.InsuranceId"><i class="fa-solid fa-trash-can"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <partial name="_PaginationPartial" />
    </div>
</div>