PojisteniApp2/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using PojisteniApp2.Data;
using PojisteniApp2.Helpers;
using PojisteniApp2.Models;

namespace PojisteniApp2.Controllers
{
    public class PeopleController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly INotyfService _notyf;
        private readonly float _imageMaxSize;
        private readonly string _defaultImagePath;
        private readonly string _genericErrorMessage = "Opravte zadaná data";

		public PeopleController(ApplicationDbContext context, INotyfService notyf, IConfiguration configuration)
        {
            _context = context;
            _notyf = notyf;
            _imageMaxSize = configuration.GetValue<float>("Person:ImageMaxSize");
            _defaultImagePath = configuration?.GetValue<string>("Person:DefaultImagePath") ?? "/images/img-person-default.png";
		}

        // GET: People
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            // Sort based on tutorial: https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-7.0#add-sorting-functionality-to-the-index-method
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "descending" : "";
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            var people = (IQueryable<Person>)_context.Person;

            if (!String.IsNullOrEmpty(searchString))
            {
                people = people.Where(e => e.LastName.Contains(searchString) || e.FirstName.Contains(searchString));
            }

            if (sortOrder == "descending")
            {
                people = people.OrderByDescending(e => e.LastName)
                                .ThenByDescending(e => e.FirstName)
                                .ThenByDescending(e => e.City)
                                .ThenByDescending(e => e.Street);
            }
            else
            {
                people = people.OrderBy(e => e.LastName)
                                .ThenBy(e => e.FirstName)
                                .ThenBy(e => e.City)
                                .ThenBy(e => e.Street);
            }

            int pageSize = 3;
            return View(await PaginatedList<Person>.CreateAsync(people.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: People/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Person == null)
            {
                return NotFound();
            }

            var person = await _context.Person
                .Include(p => p.Insurances) // Find related insurances
                .ThenInclude(i => i.InsuranceType) // Find insurance type
                .AsNoTracking() // Improves performance returned entities won't be updated
                .FirstOrDefaultAsync(m => m.PersonId == id);
            if (person == null)
            {
                return NotFound();
            }

            // Save image URL to display into ViewBag
            ViewBag.ImageDataUrl = CreateImageURL(person.ImageData);

			// Assign string "disabled" if current user is neither author nor admin
            ViewBag.Disabled = UserHelper.IsAuthorOrAdmin(User, person) ? string.Empty : "disabled";

            return View(person);
        }

        // GET: People/Create
        public IActionResult Create()
        {
            // Default image to display in view
            ViewBag.ImageDataUrl = _defaultImagePath;
            
            // Profile image max size for client validation
            ViewBag.ImageMaxSize = _imageMaxSize;

			// Assign string "disabled" if no user logged in
			ViewBag.Disabled = UserHelper.IsLoggedUser(User) ? string.Empty : "disabled";

			return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Authorize]
		public async Task<IActionResult> Create([Bind("PersonId,FirstName,LastName,Email,Phone,Street,City,PostalCode")] Person person)
        {
            // Default image to display in view
            ViewBag.ImageDataUrl = _defaultImagePath;
            
            // Profile image max size for client validation
            ViewBag.ImageMaxSize = _imageMaxSize;

			// No disabled functionality for POST method of Create action needed
			ViewBag.Disabled = string.Empty;

			// Save provided image to ImageData
			if (Request.Form.Files.Count > 0) // Image provided by user
            {
                IFormFile file = Request.Form.Files[0];
                if (IsImage(file)) // Provided file is an image file
                {
                    if (IsInSizeRange(_imageMaxSize, file)) 
                    {
                        person.ImageData = FileToByteArray(file);
                    }
                    else // Image is larger than set limit
                    {
                        ModelState.AddModelError("ImageData", $"Maximální velikost obrázku je {_imageMaxSize} MB");
                        _notyf.Error(_genericErrorMessage);
                        return View(person);
                    }
                }
                else // is not an image
                {
                    ModelState.AddModelError("ImageData", "Vybraný soubor musí být obrázek");
                    _notyf.Error(_genericErrorMessage);
                    return View(person);
                }
            }

            // Server side validations
            RunServerValidations(person);

			if (ModelState.IsValid)
            {
                // Set currently logged in user's id as AuthorId
                person.AuthorId = UserHelper.GetUserId(User);
				_context.Add(person);
                await _context.SaveChangesAsync();
                _notyf.Success($"Přidán pojištěnec<br>{person.FirstName} {person.LastName}");
                return RedirectToAction(nameof(Details), new { id = person.PersonId});
            }
            _notyf.Error(_genericErrorMessage);
            return View(person);
        }

        // GET: People/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Person == null)
            {
                return NotFound();
            }

            var person = await _context.Person.FindAsync(id);
            if (person == null)
            {
                return NotFound();
            }

            // Save image URL to display into ViewBag
            ViewBag.ImageDataUrl = CreateImageURL(person.ImageData);
            
            // Profile image max size for client validation
            ViewBag.ImageMaxSize = _imageMaxSize;
            
            // Saves URL user is coming from to be used in POST Edit action
            TempData["PreviousUrl"] = Request.Headers["Referer"].ToString();

			// Assign string "disabled" if current user is neither author nor admin
			ViewBag.Disabled = UserHelper.IsAuthorOrAdmin(User, person) ? string.Empty : "disabled";

            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Authorize]
		public async Task<IActionResult> Edit(int id, [Bind("PersonId,FirstName,LastName,Email,Phone,Street,City,PostalCode")] Person person)
        {
            if (id != person.PersonId)
            {
                return NotFound();
            }

            // Profile image max size for client validation
            ViewBag.ImageMaxSize = _imageMaxSize;

            // No disabled functionality for POST method of Edit action needed
            ViewBag.Disabled = string.Empty;

			// Save provided image to ImageData
			if (Request.Form.Files.Count == 0) // Image not provided by user
            {
                // Find existing image data in DB and set it to person.ImageData
                SetExistingImageData(person);
            }
            else // Image provided by user
            {
                IFormFile file = Request.Form.Files[0];
                if (IsImage(file)) // Provided file is an image file
                {
                    if (IsInSizeRange(_imageMaxSize, file))
                    {
                        person.ImageData = FileToByteArray(file);
                    }
                    else // Image is larger than set limit
                    {
                        ModelState.AddModelError("ImageData", $"Maximální velikost obrázku je {_imageMaxSize} MB");
                        RetrieveExistingImageData(person);
                        _notyf.Error(_genericErrorMessage);
                        return View(person);
                    }
                }
                else // is not an image
                {
                    ModelState.AddModelError("ImageData", "Vybraný soubor musí být obrázek");
                    RetrieveExistingImageData(person);

PojisteniApp2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inshuro</title>
    <link rel="icon" href="~/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PojisteniApp2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand d-flex justify-content-center align-items-center" asp-area="" asp-controller="Home" asp-action="Index"><img id="navbar-logo" src="~/images/img-logo-inshuro.png" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index"><i class="fa-solid fa-user"></i> Pojištěnci</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Insurances" asp-action="Index"><i class="fa-solid fa-file-contract"></i> Pojištění</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Inshuro
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @* Fontawesome online source if needed *@
    @*<script src="https://kit.fontawesome.com/909536fde6.js" crossorigin="anonymous"></script>*@
    <script src="~/lib/fontawesome-free-6.4.0-web/js/all.js"></script>
    <script src="~/lib/inputmask/dist/inputmask.min.js"></script>
    <script src="~/lib/inputmask/dist/bindings/inputmask.binding.js"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PojisteniApp2/Views/Shared/_PaginationPartial.cshtml
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<div class="row text-center">
    <div class="col">
        <div class="btn-group">
            <a asp-action="Index"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-pageNumber="@(Model.PageIndex - 1)"
               asp-route-currentFilter="@ViewData["CurrentFilter"]"
               class="btn btn-outline-secondary @prevDisabled">
               <i class="fa-solid fa-chevron-left"></i>
            </a>
            <a asp-action="Index"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-pageNumber="@(Model.PageIndex + 1)"
               asp-route-currentFilter="@ViewData["CurrentFilter"]"
               class="btn btn-outline-secondary @nextDisabled">
               <i class="fa-solid fa-chevron-right"></i>
            </a>
        </div>
    </div>
</div>

PojisteniApp2/Views/Shared/_SearchPartial.cshtml
<form asp-action="Index" method="get">
    <div class="form-actions">
        <div>
            <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" placeholder="Jméno nebo příjmení" class="mb-1" />
            <button type="submit" class="btn btn-sm btn-outline-secondary mb-1"><i class="fa-solid fa-magnifying-glass"></i></button>
            <a asp-action="Index" class="btn btn-sm btn-outline-secondary mb-1"><i class="fa-solid fa-xmark"></i></a>
        </div>
    </div>
</form>